### ISSUE TITLE
boost version

### ISSUE THREAD

**Issue by svenmh** [thezbyg/gpick#132]
Perhaps there can be a boost version check too.  Boost 1.53.0 that came with my system caused core dumps, but building boost 1.61 did the trick.

**Comment by thezbyg** [comment]
Was the 1.53 version built with the older gcc version by any chance? If it was built with pre-5.0 gcc, then that could be the cause of core dumps.
I added the version check, but I am not sure what minimal version of boost can be used, because downloading boost 1.53 source, and building it with the same compiler used to compile Gpick, did not cause any issues.
