### ISSUE TITLE
Segmentation Fault on Ubuntu 16.04

### ISSUE THREAD

**Issue by NTpspE** [thezbyg/gpick#144]
Hi there, 

I have been using and enjoying gpick across my ubuntu desktop and laptop, but today it suddenly refused to start. 

When I try launch via terminal the output is: "Segmentation fault (core dumped)".

I'm using the version available in the ubuntu repos, is there another version I can try from an updated ppa, or a way to debug this? 

Only real difference between the laptop (with the issue) and my desktop (no issue) is that the laptop is Intel whereas the desktop is AMD.

Many Thanks,
Nathan

**Comment by thezbyg** [comment]
Hi,
I just created a PPA with debug build of 0.2.5 version here: https://launchpad.net/~thezbyg/+archive/ubuntu/ppa/+packages

Please try running Gpick under gdb. Once segmentation fault occurs, run **where** command and paste full gdb output here. Here is a small usage gdb manual:
https://www.cs.rochester.edu/~nelson/courses/csc_173/review/gdb.html

You could also try renaming /home/USERNAME/.config/gpick/ directory to /home/USERNAME/.config/gpick-tmp/ and then running Gpick. If this fixes segmentation faults, then either configuration or stored palette file is somehow corrupted.

**Comment by thezbyg** [comment]
I guess it is too late, but it would be great if you could upload that crash inducing autosave.gpa file for analysis and testing with current Gpick version. If the file is gone and this issue ever repeats, please reopen this issue and attach offending autosave.gpa file.

**Comment by NTpspE** [comment]
Hi Thezbyg, 

I did still have the corrupt autosave.gpa file in my recycling bin, so please find this attached. 
[autosave.gpa.zip](https://github.com/thezbyg/gpick/files/1288367/autosave.gpa.zip)

**Comment by thezbyg** [comment]
Thanks. The file is indeed corrupted and looks like either Gpick crashed while writing it, or multiple Gpick instances wrote to it at the same time. After a small change to loading function (commit 234fd19c109c15b308bf43ade0e6cc58c9581bb0) I managed to recover at least part of that file:  [autosave.zip](https://github.com/thezbyg/gpick/files/1289657/autosave.zip).
I will have to investigate if exiting multiple Gpick instances at the same time can cause this, and if it turns out to be the cause I will fix it.
