### ISSUE TITLE
Copy/paste multiple colors

### ISSUE THREAD

**Issue by prokoudine** [thezbyg/gpick#180]
It's possible to select multiple colors in the colors list to delete them. However, only the first selected color can be copy-pasted.

**Comment by thezbyg** [comment]
I need some clarification, because currently multiple colors can be copied by selecting them and pressing _Ctrl+C_ or using _Copy to clipboard_ menu item. Results can be pasted into some other application like text editor. I assume that you are asking for ability to paste multiple colors into Gpick palette? This is not currently implemented but shouldn't be hard to do.

**Comment by prokoudine** [comment]
No, here is what I mean.

1. Select multiple colors in the right pane
2. Ctrl+C
3. Ctrl+V

I expected multiple colors to be appended to that list. Instead, only the first selected color is copy-pasted.

**Comment by thezbyg** [comment]
Done. Please test if copying/pasting works as you expect.

**Comment by prokoudine** [comment]
Seems to work as expected, thank you!
