### ISSUE TITLE
Export with colornames / last version

### ISSUE THREAD

**Issue by Nemesis77swe** [thezbyg/gpick#185]
Is there anyway to export the color code-names with the color codes? (the names I wrote under the name row)?

currently it only exports the codes.
I'm also unsure if I got the latest version, can't find any version information here, and the screenshots here isn't looking like mine..
I got 0.2.6rc1

**Comment by thezbyg** [comment]
Hi, I assume that you tried to export colors as a text file, because all other export types include names by default or have an option to include names.
I have now enabled "Include color names" check box when export format is set to text file. When this option is set, each exported text line is made of serialized color code, a single space character and color name. Like this:
```
#312D62 Twilight
#63625D Charcoal grey
#818058 Brown grey
#979753 Khaki
#ABAB4D Light olive
```
The same output could be achieved in older versions by creating custom converter and selecting it when exporting.
