### ISSUE TITLE
Gpick not showing any UI

### ISSUE THREAD

**Issue by aavelor** [thezbyg/gpick#195]
I'm using Gpick 0.2.6 on Kubuntu 21.04. On first install everything was ok until one day I tried to change the View layout. As soon as I clicked other option, Gpick's UI went blank. I cant see anything but me top menu and the bottom right text saying I have some colors on the list.

I tried installing, uninstalling, cleaning cache and garbage files with bleach but nothing seems to work. Oddly enough, a couple of days ago I opened it and the UI was back, so I decided to try and see if the issue was a one time bug but found I was able to replicate it again.

![Screenshot_20210609_093848](https://user-images.githubusercontent.com/58258/121375696-8a2b1c80-c906-11eb-82b6-7070cac11d6a.png)

The problem seems to persist on Wayland (I'm using X11 at the moment).

**Comment by thezbyg** [comment]
Hi,
layout switching menu has a bug which causes invalid layout configuration. This is already fixed in 9c62c2a3a7a99e2cfc3464b2b9549a55440bc925.

To restore UI before fixed Gpick version is available, open _~/.config/gpick/settings.xml_ with text editor and remove layout configuration value which starts with ```<layout type="string">``` and ends with ```</layout>```. This will reset layout back to default value. Or delete _~/.config/gpick/settings.xml_ to reset all settings.

**Comment by aavelor** [comment]
Thank you. I was looking for some kind of persistent config file but didn't know where to look for it. I'll close the issue and edit the title so others can  look for it.
